/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicalUserInterface;

import java.math.BigDecimal;

    
/**
 *
 * @author Wind Raider Zero
 */

public class MainInterface extends javax.swing.JFrame {
    
    private module.DBConsole db;
    private calculation.ZScoreSystemCalculation zScore;
    
    private String childID;
    private double[][]wfaList;
    private double[][]hfaList;
    private double[][]wflList;
    private String dateOfBirth;
    private String radioInspector;
    private String []childIDList;
    
    private String query;
    String[][]result;
    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        
        initComponents();
        setResizable(false);
        setLocation(250,10);
        zScore = new calculation.ZScoreSystemCalculation();
    }
    
    public MainInterface(module.DBConsole db, String childID){
        this();
        this.db=db;
        
        refreshIDList();
        idList.setSelectedItem(childID);
        
        refreshInterface(childID);
    }

    public void refreshIDList(){
        String temp[][] = db.doQuery("SELECT id FROM child ORDER BY id ASC",0);
        
        childIDList = new String[temp.length*temp[0].length];
        
        for(int i=0;i<temp.length;i++){
            for(int j=0;j<temp[0].length;j++){
                childIDList[(temp[0].length*i)+j] = temp[i][j];
            }
            
            //System.arraycopy(temp[i], 0, childIDList, (i*temp[0].length)-1, temp[i].length);
        }
        idList.setModel(new javax.swing.DefaultComboBoxModel<>(childIDList));
    }
    
    private void refreshInterface(String childID){
        this.childID=childID;
        
        
        String [][]dataChild = db.doQuery("SELECT * FROM child where id = '"+childID+"'", 0);
        String [][]dataVisit = db.doQuery("SELECT * FROM visit where child_id = '"+childID+
                "' and visit_date = (SELECT MAX(visit_date) FROM visit WHERE child_id='"+childID+"')", 0);
        
        setGeneralInfo(dataChild[0]);
        this.dateOfBirth = dataChild[0][4];
        zScore.person = new data.Person(
                dataChild[0][1],
                dataChild[0][2].contains("laki"),
                dataChild[0][4], 
                dataVisit[0][1],
                Double.parseDouble(dataVisit[0][2]),
                Double.parseDouble(dataVisit[0][3])
        );
        
        setLatestInfo(dataVisit[0]);
        
        double[]z = {
            zScore.countWFA(zScore.person.isMale(), zScore.person.getAgeByDay(), zScore.person.getWeight()),
            zScore.countHFA(zScore.person.isMale(), zScore.person.getAgeByDay(), zScore.person.getHeight()),
            zScore.person.getAgeByDay() < 730 ?
            zScore.countWFL(zScore.person.isMale(), zScore.person.getWeight(), zScore.person.getHeight()) :
            zScore.countWFH(zScore.person.isMale(), zScore.person.getWeight(), zScore.person.getHeight())
        };
        String []zStatus = {
            zScore.getWFAZScoreClassification(z[0]),
            zScore.getHFAZScoreClassification(z[1]),
            zScore.getWFLZScoreClassification(z[2])
        };
        
        setLatestResult(new String[]{
            Double.toString(new BigDecimal(z[0])
                            .setScale(3, BigDecimal.ROUND_HALF_UP)
                            .doubleValue()),
            zStatus[0],
            Double.toString(new BigDecimal(z[1])
                            .setScale(3, BigDecimal.ROUND_HALF_UP)
                            .doubleValue()),
            zStatus[1],
            Double.toString(new BigDecimal(z[2])
                            .setScale(3, BigDecimal.ROUND_HALF_UP)
                            .doubleValue()),
            zStatus[2]
        });
        this.buttonGroup1.add(this.wfaRadio);
        this.buttonGroup1.add(this.hfaRadio);
        this.buttonGroup1.add(this.wflRadio);
        
        wfaRadio.setSelected(true);
        radioInspector="wfa";
        createWFAGraphic();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always 
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        weightField = new javax.swing.JLabel();
        heightField = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastVisitField = new javax.swing.JLabel();
        ageField = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lfaZScoreField = new javax.swing.JLabel();
        wflZScoreField = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        wfaStatusField = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lfaStatusField = new javax.swing.JLabel();
        wflStatusField = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        wfaZScoreField = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        nameField = new javax.swing.JLabel();
        genderField = new javax.swing.JLabel();
        dobField = new javax.swing.JLabel();
        motherField = new javax.swing.JLabel();
        idList = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        graphicPanelFX = new graphicalUserInterface.GraphicPanel();
        jPanel8 = new javax.swing.JPanel();
        wflRadio = new javax.swing.JRadioButton();
        hfaRadio = new javax.swing.JRadioButton();
        wfaRadio = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setToolTipText("Latest Information");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Latest Information");

        weightField.setText(": kg");

        heightField.setText(": cm");

        jLabel15.setText("Age ");

        jLabel16.setText("Last Visit");

        jLabel2.setText("Weight");

        jLabel3.setText("Length/Height");

        lastVisitField.setText(": 2017-12-31");

        ageField.setText(": month");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastVisitField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(weightField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(weightField)
                    .addComponent(jLabel15)
                    .addComponent(ageField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(heightField)
                    .addComponent(jLabel16)
                    .addComponent(lastVisitField)))
        );

        lfaZScoreField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lfaZScoreField.setText("jLabel7");

        wflZScoreField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wflZScoreField.setText("jLabel7");

        wfaStatusField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wfaStatusField.setText("Severely Underweight");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Status");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Z Score");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(jLabel11))
        );

        lfaStatusField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lfaStatusField.setText("jLabel17");

        wflStatusField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wflStatusField.setText("jLabel17");

        jLabel4.setText("Weight for Age");

        jLabel5.setText("Length for Age");

        jLabel6.setText("Weight for Length");

        wfaZScoreField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wfaZScoreField.setText("jLabel7");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wfaZScoreField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lfaZScoreField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wflZScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wfaStatusField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lfaStatusField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wflStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(wfaZScoreField)
                    .addComponent(wfaStatusField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lfaZScoreField)
                    .addComponent(lfaStatusField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(wflZScoreField)
                    .addComponent(wflStatusField))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("add visit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel14.setText("ID");

        jLabel24.setText("Date of Birth");

        jLabel25.setText("Mother Name");

        jLabel22.setText("Name");

        jLabel23.setText("Gender");

        nameField.setText(": ");

        genderField.setText(": ");

        dobField.setText(":");

        motherField.setText(":");

        idList.setMaximumRowCount(4);
        idList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(motherField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dobField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genderField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(idList, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(genderField)
                        .addGap(18, 18, 18)
                        .addComponent(dobField)
                        .addGap(18, 18, 18)
                        .addComponent(motherField))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(idList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        wflRadio.setText("Weight for Length");
        wflRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wflRadioActionPerformed(evt);
            }
        });

        hfaRadio.setText("Height for Age");
        hfaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hfaRadioActionPerformed(evt);
            }
        });

        wfaRadio.setText("Weight for Age");
        wfaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wfaRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wfaRadio)
                .addGap(18, 18, 18)
                .addComponent(hfaRadio)
                .addGap(18, 18, 18)
                .addComponent(wflRadio)
                .addGap(164, 164, 164))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hfaRadio)
                    .addComponent(wfaRadio)
                    .addComponent(wflRadio))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(graphicPanelFX, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphicPanelFX, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Add children data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setGeneralInfo(String[]data){
        if(data.length<1)
            return;
        //this.idField.setText(": "+data[0]);
        this.nameField.setText(": "+data[1]);
        this.genderField.setText(": "+data[2]);
        this.dobField.setText(": "+data[4]);
        this.motherField.setText(": "+data[3]);
    }
    
    private void setLatestInfo(String[]data){
        if(data.length<1)
            return;
        this.ageField.setText(": "+zScore.person.getAge()+" Month");
        this.lastVisitField.setText(": "+data[1]);
        this.weightField.setText(": "+data[2]+" kg");
        this.heightField.setText(": "+data[3]+" cm");
    }
    
    private void setLatestResult(String[]data){
        this.wfaZScoreField.setText(data[0]);
        this.wfaStatusField.setText(data[1]);
        
        this.lfaZScoreField.setText(data[2]);
        this.lfaStatusField.setText(data[3]);
        
        this.wflZScoreField.setText(data[4]);
        this.wflStatusField.setText(data[5]);
    }
    
    private void createWFAGraphic(){
        String[][]queryResult = populateData();
        
        String [][] z = new String[queryResult.length][2];
        for(int i=0;i<queryResult.length;i++){
            z[i][0] = Integer.toString(zScore.dailyUnitCalculationOf(dateOfBirth, queryResult[i][1]));
            z[i][1] = Double.toString(zScore.countWFA(zScore.person.isMale(), 
                    Integer.parseInt(z[i][0]), 
                    Double.parseDouble(queryResult[i][2])));
        }
        graphicPanelFX.refreshGraphic(z, "Weight for Age Z-Score", "weight for age","age (day)","z score");
    }
    
    private void createHFAGraphic(){
        String[][]queryResult = populateData();
        
        String [][] z = new String[queryResult.length][2];
        for(int i=0;i<queryResult.length;i++){
            z[i][0] = Integer.toString(zScore.dailyUnitCalculationOf(dateOfBirth, queryResult[i][1]));
            z[i][1] = Double.toString(zScore.countHFA(zScore.person.isMale(), 
                    Integer.parseInt(z[i][0]), 
                    Double.parseDouble(queryResult[i][3])));
        }
        graphicPanelFX.refreshGraphic(z, (zScore.person.getAgeByDay()<730? "Length":"Height")+" for Age Z-Score", (zScore.person.getAgeByDay()<730? "length":"height")+" for age","age (day)","z score");
    }
    
    private void createWFLGraphic(){
        String[][]queryResult = populateData();
        
        String [][] z = new String[queryResult.length][2];
        for(int i=0;i<queryResult.length;i++){
            z[i][0] = Integer.toString(zScore.dailyUnitCalculationOf(dateOfBirth, queryResult[i][1]));
            z[i][1] = Double.toString(zScore.countWFL(zScore.person.isMale(),Double.parseDouble(queryResult[i][2]),Double.parseDouble(queryResult[i][3])));
        }
        
        graphicPanelFX.refreshGraphic(z, "Weight for "+(zScore.person.getAgeByDay()<730? "Length":"Height")+" Z-Score", 
                "weight for "+(zScore.person.getAgeByDay()<730? "length":"height"),"height (cm)","z score");
    }
    
    private String[][]populateData(){
        if (childID.equals(""))
            return null;
        query = null;
        System.gc();
        query = "SELECT * from visit where child_ID = '"+childID+"' ORDER BY visit_date";
        result=null;
        System.gc();
        result = db.doQuery(query, 1);
        return result;
    }
    
    public void commandToUseByAddVisitClass(){
        createWFAGraphic();
        this.wfaRadio.setSelected(true);
    }
    
    private void wfaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wfaRadioActionPerformed
        if(radioInspector.equals("wfa"))
            return;
        radioInspector="wfa";
        
        this.createWFAGraphic();
    }//GEN-LAST:event_wfaRadioActionPerformed

    private void hfaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hfaRadioActionPerformed
        if(radioInspector.equals("hfa"))
            return;
        radioInspector="hfa";
        
        this.createHFAGraphic();
    }//GEN-LAST:event_hfaRadioActionPerformed

    private void wflRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wflRadioActionPerformed
        if(radioInspector.equals("wfl"))
            return;
        radioInspector="wfl";
        
        this.createWFLGraphic();
    }//GEN-LAST:event_wflRadioActionPerformed

    private void idListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idListActionPerformed
        this.refreshInterface(idList.getSelectedItem().toString());
    }//GEN-LAST:event_idListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        new AddVisit(db,this,childID).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new InputForm(db,this,childID).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface(new module.DBConsole("127.0.0.1","opensrpdummy","root",""),"CH002").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dobField;
    private javax.swing.JLabel genderField;
    private graphicalUserInterface.GraphicPanel graphicPanelFX;
    private javax.swing.JLabel heightField;
    private javax.swing.JRadioButton hfaRadio;
    private javax.swing.JComboBox<String> idList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lastVisitField;
    private javax.swing.JLabel lfaStatusField;
    private javax.swing.JLabel lfaZScoreField;
    private javax.swing.JLabel motherField;
    private javax.swing.JLabel nameField;
    private javax.swing.JLabel weightField;
    private javax.swing.JRadioButton wfaRadio;
    private javax.swing.JLabel wfaStatusField;
    private javax.swing.JLabel wfaZScoreField;
    private javax.swing.JRadioButton wflRadio;
    private javax.swing.JLabel wflStatusField;
    private javax.swing.JLabel wflZScoreField;
    // End of variables declaration//GEN-END:variables
}
